doctrine_migrations:
    storage:
        table_storage:
            table_name: 'migration_versions'
    migrations_paths:
        DoctrineMigrations: 'src/Infrastructure/Migrations'
    organize_migrations: BY_YEAR
    custom_template: '%kernel.project_dir%/config/packages/doctrine_migrations.template'
