<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true],
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true, 'test' => true],
    FriendsOfBehat\SymfonyExtension\Bundle\FriendsOfBehatSymfonyExtensionBundle::class => ['test' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['dev' => true, 'test' => true],
    BehatNelmioDescriber\BehatNelmioDescriberBundle::class => ['dev' => true, 'test' => true],
    SymfonyBundles\RedisBundle\SymfonyBundlesRedisBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    BehatApiContext\BehatApiContextBundle::class => ['test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    BehatDoctrineFixtures\BehatDoctrineFixturesBundle::class => ['test' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Sentry\SentryBundle\SentryBundle::class => ['all' => true],
    Macpaw\SymfonyMessengerBundle\SymfonyMessengerBundle::class => ['all' => true],
    RequestDtoResolver\RequestDtoResolverBundle::class => ['all' => true],
    BehatMessengerContext\BehatMessengerContextBundle::class => ['test' => true],
    BehatRedisContext\BehatRedisContextBundle::class => ['test' => true],
    SymfonyHealthCheckBundle\SymfonyHealthCheckBundle::class => ['all' => true],
    ExtendedMockHttpClient\ExtendedMockHttpClientBundle::class => ['test' => true],
    BehatHttpMockContext\BehatHttpMockContextBundle::class => ['test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
];
